### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by ferllings** [BillBuilt/wails-vite-svelte-template#2]
Hello,

I just did a fresh install on MacOS and I have this error.
Anybody else have it?

```
wails dev
Wails CLI v2.0.0-beta.35


Executing: go mod tidy -compat=1.17
Executing: wails generate module
Building application for development...
  - Installing frontend dependencies: Done.
  - Compiling frontend: Done.
  - Compiling application: Done.
  - Packaging application: Done.

Watching (sub)/directory: /Users/cedric/Documents/monitor
Using DevServer URL: http://localhost:34115
Using reload debounce setting of 100 milliseconds
INF | Serving assets from disk: /Users/cedric/Documents/monitor/frontend/dist
Added new directory to watcher: /Users/cedric/Documents/monitor/frontend/src/wailsjs/go
DEB | [DevWebServer] Serving DevServer at http://localhost:34115
DEB | [AssetHandler] [AssetHandler] Loading file 'index.html'
unexpected fault address 0x208dad000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x208dad000 pc=0x4069678]

goroutine 1 [running, locked to thread]:
runtime.throw({0x44cd9a7?, 0x8103e30?})
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/panic.go:992 +0x71 fp=0xc0001d38e8 sp=0xc0001d38b8 pc=0x4038d91
runtime.sigpanic()
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/signal_unix.go:815 +0x1e5 fp=0xc0001d3938 sp=0xc0001d38e8 pc=0x404e205
runtime.memmove()
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/memmove_amd64.s:111 +0xb8 fp=0xc0001d3940 sp=0xc0001d3938 pc=0x4069678
runtime.gobytes(0x443c960?, 0x6000)
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/string.go:321 +0x73 fp=0xc0001d3990 sp=0xc0001d3940 pc=0x4053c93
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin._Cfunc_GoBytes(...)
	_cgo_gotypes.go:269
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.processURLRequest.func1(0xc0000021a0?, 0x6000?)
	/Users/cedric/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.35/internal/frontend/desktop/darwin/frontend.go:400 +0x45 fp=0xc0001d39c8 sp=0xc0001d3990 pc=0x4375e45
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.processURLRequest(0x6000026006c0, 0x600000c549a1, 0x0?, 0xc0001d3a98?, 0x4009a66?, 0x21a0?)
	/Users/cedric/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.35/internal/frontend/desktop/darwin/frontend.go:400 +0x45 fp=0xc0001d3a38 sp=0xc0001d39c8 pc=0x4375c65
_cgoexp_d6fc8ef76700_processURLRequest(0x4042ac5?)
	_cgo_gotypes.go:714 +0x33 fp=0xc0001d3a78 sp=0xc0001d3a38 pc=0x4379253
runtime.cgocallbackg1(0x4379220, 0xc0001d3c30?, 0x0)
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/cgocall.go:314 +0x2bd fp=0xc0001d3b48 sp=0xc0001d3a78 pc=0x400997d
runtime.cgocallbackg(0xc0000021a0?, 0x300000002?, 0xc0000021a0?)
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/cgocall.go:233 +0x109 fp=0xc0001d3bd8 sp=0xc0001d3b48 pc=0x4009609
runtime.cgocallbackg(0x4379220, 0x208da81b8, 0x0)
	<autogenerated>:1 +0x2f fp=0xc0001d3c00 sp=0xc0001d3bd8 pc=0x406a9af
runtime.cgocallback(0x4009485, 0x43fea40, 0xc0001d3c90)
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/asm_amd64.s:971 +0xb4 fp=0xc0001d3c28 sp=0xc0001d3c00 pc=0x4068574
runtime.systemstack_switch()
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/asm_amd64.s:436 fp=0xc0001d3c30 sp=0xc0001d3c28 pc=0x4066540
runtime.cgocall(0x43fea40, 0xc0001d3c90)
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/cgocall.go:167 +0x85 fp=0xc0001d3c68 sp=0xc0001d3c30 pc=0x4009485
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin._Cfunc_Run(0x6000026006c0, 0x60000000c790)
	_cgo_gotypes.go:417 +0x45 fp=0xc0001d3c90 sp=0xc0001d3c68 pc=0x4370545
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.(*Window).Run.func1(0xc0001a5a20?, 0xe?)
	/Users/cedric/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.35/internal/frontend/desktop/darwin/window.go:124 +0x4c fp=0xc0001d3cd0 sp=0xc0001d3c90 pc=0x43779cc
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.(*Window).Run(0xc0001e2e10?, {0xc0001a5a20?, 0x458c890?})
	/Users/cedric/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.35/internal/frontend/desktop/darwin/window.go:124 +0x3b fp=0xc0001d3d00 sp=0xc0001d3cd0 pc=0x43778bb
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.(*Frontend).Run(0xc000254a20, {0x45915a8, 0xc0002595f0})
	/Users/cedric/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.35/internal/frontend/desktop/darwin/frontend.go:152 +0x148 fp=0xc0001d3d48 sp=0xc0001d3d00 pc=0x4374668
github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Run(0xc0001e3200, {0x45915a8?, 0xc0002595f0})
	/Users/cedric/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.35/internal/frontend/devserver/devserver.go:135 +0x787 fp=0xc0001d3ee8 sp=0xc0001d3d48 pc=0x43f5887
github.com/wailsapp/wails/v2/internal/appng.(*App).Run(0xc00018e550)
	/Users/cedric/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.35/internal/appng/app_dev.go:48 +0x31 fp=0xc0001d3f20 sp=0xc0001d3ee8 pc=0x43fc2b1
github.com/wailsapp/wails/v2.Run(0x400bed9?)
	/Users/cedric/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.35/wails.go:24 +0x33 fp=0xc0001d3f38 sp=0xc0001d3f20 pc=0x43fd6b3
main.main()
	/Users/cedric/Documents/monitor/main.go:21 +0x28d fp=0xc0001d3f80 sp=0xc0001d3f38 pc=0x43fdacd
runtime.main()
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/proc.go:250 +0x212 fp=0xc0001d3fe0 sp=0xc0001d3f80 pc=0x403b472
runtime.goexit()
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0001d3fe8 sp=0xc0001d3fe0 pc=0x4068781

goroutine 19 [chan receive]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.(*Frontend).startRequestProcessor(0x0?)
	/Users/cedric/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.35/internal/frontend/desktop/darwin/frontend.go:101 +0x5a
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.NewFrontend
	/Users/cedric/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.35/internal/frontend/desktop/darwin/frontend.go:86 +0x2cd

goroutine 20 [chan receive]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.(*Frontend).startMessageProcessor(0x0?)
	/Users/cedric/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.35/internal/frontend/desktop/darwin/frontend.go:96 +0x59
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.NewFrontend
	/Users/cedric/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.35/internal/frontend/desktop/darwin/frontend.go:89 +0x30a

goroutine 21 [chan receive]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.(*Frontend).startCallbackProcessor(0x0?)
	/Users/cedric/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.35/internal/frontend/desktop/darwin/frontend.go:106 +0x3d
created by github.com/wailsapp/wails/v2/internal/frontend/desktop/darwin.NewFrontend
	/Users/cedric/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.35/internal/frontend/desktop/darwin/frontend.go:90 +0x34a

goroutine 22 [IO wait]:
internal/poll.runtime_pollWait(0x8144ec8, 0x72)
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc00029c000?, 0x402bfe5?, 0x0)
	/usr/local/Cellar/go/1.18.1/libexec/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.18.1/libexec/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Accept(0xc00029c000)
	/usr/local/Cellar/go/1.18.1/libexec/src/internal/poll/fd_unix.go:614 +0x22c
net.(*netFD).accept(0xc00029c000)
	/usr/local/Cellar/go/1.18.1/libexec/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc0002a4000)
	/usr/local/Cellar/go/1.18.1/libexec/src/net/tcpsock_posix.go:139 +0x28
net.(*TCPListener).AcceptTCP(0xc0002a4000)
	/usr/local/Cellar/go/1.18.1/libexec/src/net/tcpsock.go:275 +0x3d
github.com/labstack/echo/v4.tcpKeepAliveListener.Accept({0x40439a0?})
	/Users/cedric/go/pkg/mod/github.com/labstack/echo/v4@v4.7.2/echo.go:941 +0x1d
net/http.(*Server).Serve(0xc00024e0e0, {0x4590f60, 0xc000294008})
	/usr/local/Cellar/go/1.18.1/libexec/src/net/http/server.go:3039 +0x385
github.com/labstack/echo/v4.(*Echo).Start(0xc0001df200, {0xc0000280ca, 0xf})
	/Users/cedric/go/pkg/mod/github.com/labstack/echo/v4@v4.7.2/echo.go:647 +0xce
github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Run.func4(0x0?, 0x0?)
	/Users/cedric/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.35/internal/frontend/devserver/devserver.go:117 +0x36
created by github.com/wailsapp/wails/v2/internal/frontend/devserver.(*DevWebServer).Run
	/Users/cedric/go/pkg/mod/github.com/wailsapp/wails/v2@v2.0.0-beta.35/internal/frontend/devserver/devserver.go:116 +0x69b

goroutine 35 [IO wait]:
internal/poll.runtime_pollWait(0x8144dd8, 0x72)
	/usr/local/Cellar/go/1.18.1/libexec/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc00029c080?, 0xc0002ae000?, 0x0)
	/usr/local/Cellar/go/1.18.1/libexec/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/Cellar/go/1.18.1/libexec/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc00029c080, {0xc0002ae000, 0x1000, 0x1000})
	/usr/local/Cellar/go/1.18.1/libexec/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00029c080, {0xc0002ae000?, 0xc0001bb650?, 0x4071b7e?})
	/usr/local/Cellar/go/1.18.1/libexec/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000294018, {0xc0002ae000?, 0x42ab54c?, 0xc00028c0c0?})
	/usr/local/Cellar/go/1.18.1/libexec/src/net/net.go:183 +0x45
net/http.(*connReader).Read(0xc00028e2d0, {0xc0002ae000, 0x1000, 0x1000})
	/usr/local/Cellar/go/1.18.1/libexec/src/net/http/server.go:780 +0x16d
bufio.(*Reader).fill(0xc000280180)
	/usr/local/Cellar/go/1.18.1/libexec/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).ReadSlice(0xc000280180, 0x0?)
	/usr/local/Cellar/go/1.18.1/libexec/src/bufio/bufio.go:371 +0x2f
bufio.(*Reader).ReadLine(0xc000280180)
	/usr/local/Cellar/go/1.18.1/libexec/src/bufio/bufio.go:400 +0x27
net/textproto.(*Reader).readLineSlice(0xc000259e30)
	/usr/local/Cellar/go/1.18.1/libexec/src/net/textproto/reader.go:57 +0x99
net/textproto.(*Reader).ReadLine(...)
	/usr/local/Cellar/go/1.18.1/libexec/src/net/textproto/reader.go:38
net/http.readRequest(0xc000294018?)
	/usr/local/Cellar/go/1.18.1/libexec/src/net/http/request.go:1029 +0x79
net/http.(*conn).readRequest(0xc0002aa000, {0x4591500, 0xc00028c080})
	/usr/local/Cellar/go/1.18.1/libexec/src/net/http/server.go:988 +0x24a
net/http.(*conn).serve(0xc0002aa000, {0x45915a8, 0xc00028e1e0})
	/usr/local/Cellar/go/1.18.1/libexec/src/net/http/server.go:1891 +0x32b
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.18.1/libexec/src/net/http/server.go:3071 +0x4db
```

**Comment by BillBuilt** [comment]
Wails very recently had a big update and I have not had a chance to see if these templates will work with it or not. When I get some time I will check, however I do believe they have done a lot of work with the internal Svelte templates and those may actually work better now. When I created these, the internal templates did not work  as I expected, and I believe did not use Vite, which is what I really wanted to use with Svelte.

**Comment by ferllings** [comment]
Thanks !

**Comment by BillBuilt** [comment]
No problem! If you nail down what's causing that, could you let me know here? Even if it isn't related to these templates? I might be facing the same problem when I eventually get around to updating my projects. I've just been pulled away from them for the time being.
